/**
 * 这是next的全局layout
 */
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: '元数据标题',
  description: 'Generated by create next app',
  keywords: 'nextjs,typescript,react',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div style={{ backgroundColor: '#007acc' }}>公共头部</div>
        {children}
      </body>
    </html>
  );
}
